
[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.git-flow]
dependencies = [
  "format",
  "build",
  "test"
]

[tasks.proto-gen]
script = { file = "${CARGO_MAKE_WORKING_DIRECTORY}/scripts/protocgen.sh", absolute_path = true }
