# This workflow helps with creating releases.
# This job will only be triggered when a tag (vX.X.x) is pushed
name: Release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v[0-9]+\\.[0-9]+\\.[0-9]+" # Official release version tags e.g. v2.0.5
      - "v[0-9]+\\.[0-9]+\\.[0-9]+-rc[0-9]+" # Release candidate tags e.g. v1.0.3-rc4
  pull_request:
    types: [opened, synchronize]

jobs:
  basic:
    uses: ./.github.com/workflows/basic.yml
  
  release:
    runs-on: ubuntu-latest
    needs: basic
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - uses: katyo/publish-crates@v1
      with:
        path: './packages/cw-umee-types'
        registry-token: ${{ secrets.CARGO_REGISTRIES_UMEE_TOKEN }}
